<template>
  <section class="bio-nexus-panel laboratory-panel">
    <div class="bio-nexus-panel-heading"><div><p class="bio-nexus-panel-eyebrow">Documentos e impresiÃ³n</p><h3>Factura, comprobante y toma de muestra</h3></div></div>
    <div class="document-grid">
      <article v-for="section in sections" :key="section.key" class="bio-nexus-section">
        <div class="bio-nexus-section-heading"><h4 class="bio-nexus-section-title">{{ section.title }}</h4></div>
        <div class="section-body">
          <label class="check"><input v-model="model[section.printField]" type="checkbox" :disabled="disabled"><span>{{ section.printLabel }}</span></label>
          <BioNexusFormField :label="section.numberLabel" :field-id="section.key+'-number'"><input v-model.number="model[section.numberField]" class="bio-nexus-field" type="number" min="0" :disabled="disabled"></BioNexusFormField>
          <BioNexusFormField v-if="section.rowsField" label="Filas mÃ¡ximas de descripciÃ³n" :field-id="section.key+'-rows'"><input v-model.number="model[section.rowsField]" class="bio-nexus-field" type="number" min="5" max="15" :disabled="disabled"></BioNexusFormField>
        </div>
      </article>
    </div>
    <article class="bio-nexus-section printer"><div class="bio-nexus-section-heading"><h4 class="bio-nexus-section-title">Impresora de toma de muestra</h4></div><div class="printer-grid"><BioNexusFormField label="Impresora tiquera" field-id="printer-type"><input v-model="model.printer_type" class="bio-nexus-field" maxlength="100" :disabled="disabled"></BioNexusFormField><BioNexusFormField label="LocalizaciÃ³n en red" field-id="printer-interface" help="Ej. //localhost/pos-80"><input v-model="model.printer_interface" class="bio-nexus-field" maxlength="100" :disabled="disabled"></BioNexusFormField></div></article>
    <article class="bio-nexus-section taxes"><div class="bio-nexus-section-heading"><h4 class="bio-nexus-section-title">Impuestos</h4><BioNexusActionButton size="sm" variant="secondary" :disabled="disabled" @click="$emit('add-tax')">Agregar impuesto</BioNexusActionButton></div><div v-if="taxes.length===0" class="bio-nexus-empty-state">No existen impuestos configurados.</div><div v-else class="tax-list"><div v-for="(tax,index) in taxes" :key="tax.localKey||tax.id" class="tax-row"><input v-model="tax.description" class="bio-nexus-field" placeholder="DescripciÃ³n" :disabled="disabled"><input v-model.number="tax.value" class="bio-nexus-field" type="number" min="0" step="0.01" :disabled="disabled"><label class="check"><input v-model="tax.only_dollars" type="checkbox" :disabled="disabled"><span>Solo dÃ³lares</span></label><label class="check"><input v-model="tax.always_subtotal" type="checkbox" :disabled="disabled"><span>Fijo subtotal</span></label><label class="check"><input v-model="tax.hide" type="checkbox" :disabled="disabled"><span>Ocultar</span></label><BioNexusActionButton size="sm" variant="danger" :disabled="disabled" @click="$emit('delete-tax',tax,index)">Eliminar</BioNexusActionButton></div></div></article>
  </section>
</template>
<script setup>
import BioNexusActionButton from "@/components/ui/BioNexusActionButton.vue";
import BioNexusFormField from "@/components/ui/BioNexusFormField.vue";
defineProps({model:{type:Object,required:true},taxes:{type:Array,default:()=>[]},disabled:{type:Boolean,default:false}});defineEmits(["add-tax","delete-tax"]);
const sections=Object.freeze([{key:"invoice",title:"Factura",printField:"print_invoice",printLabel:"Imprimir al ingresar al paciente",numberField:"invoice_number",numberLabel:"Correlativo de factura",rowsField:"rows_description_invoices"},{key:"receipt",title:"Comprobante",printField:"print_receipt",printLabel:"Imprimir al ingresar al paciente",numberField:"receipt_number",numberLabel:"Correlativo de comprobante",rowsField:"rows_description_receipt"},{key:"sample",title:"Toma de muestra",printField:"print_sample_take",printLabel:"Imprimir al ingresar al paciente",numberField:"voucher_number",numberLabel:"Correlativo de toma"}]);
</script>
<style scoped>.document-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--bio-nexus-space-3)}.section-body,.printer-grid{display:grid;gap:var(--bio-nexus-space-3);padding:var(--bio-nexus-space-4)}.printer-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.printer,.taxes{margin-top:var(--bio-nexus-space-4)}.check{display:inline-flex;align-items:center;gap:var(--bio-nexus-space-2);min-height:var(--bio-nexus-control-height);color:var(--bio-nexus-color-text-secondary);font-weight:var(--bio-nexus-font-weight-bold)}.tax-list{display:grid;gap:var(--bio-nexus-space-2);padding:var(--bio-nexus-space-3)}.tax-row{display:grid;grid-template-columns:minmax(170px,1fr) 110px repeat(3,auto) auto;gap:var(--bio-nexus-space-3);align-items:center}@media(max-width:1050px){.document-grid{grid-template-columns:1fr}.tax-row{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.printer-grid,.tax-row{grid-template-columns:1fr}}</style>