<template>
  <section class="application-settings-panel">
    <section v-show="activeTab==='regional'" id="application-settings-panel-regional" role="tabpanel" aria-labelledby="application-settings-tab-regional" class="regional-layout">
      <div class="regional-main">
        <BioNexusSectionPanel title="Contexto regional" description="Idioma y zona horaria usados como contexto general." icon="language" variant="accent">
          <div class="fields-grid"><BioNexusFormField label="Idioma y región" field-id="app-locale"><BioNexusSearchableSelect id="app-locale" v-model="model.locale" :options="localeOptions" placeholder="Seleccione idioma y región" search-placeholder="Buscar idioma..." :disabled="disabled" /></BioNexusFormField><BioNexusFormField label="Zona horaria" field-id="app-time-zone"><BioNexusSearchableSelect id="app-time-zone" v-model="model.time_zone" :options="timeZoneOptions" placeholder="Seleccione zona horaria" search-placeholder="Buscar zona horaria..." :disabled="disabled" /></BioNexusFormField></div>
        </BioNexusSectionPanel>
        <BioNexusSectionPanel title="Fecha y hora" description="Define el orden de las fechas, el ciclo horario y el inicio de semana." icon="calendar_month" variant="accent">
          <div class="fields-grid fields-grid-three"><BioNexusFormField label="Formato de fecha" field-id="app-date-format"><BioNexusSearchableSelect id="app-date-format" v-model="model.date_format" :options="dateFormatOptions" placeholder="Seleccione formato de fecha" search-placeholder="Buscar formato..." :disabled="disabled" /></BioNexusFormField><BioNexusFormField label="Formato de hora" field-id="app-hour-cycle"><BioNexusSearchableSelect id="app-hour-cycle" v-model="model.hour_cycle" :options="hourCycleOptions" placeholder="Seleccione formato de hora" search-placeholder="Buscar formato..." :disabled="disabled" /></BioNexusFormField><BioNexusFormField label="Primer día de la semana" field-id="app-first-day"><BioNexusSearchableSelect id="app-first-day" v-model="model.first_day_of_week" :options="firstDayOptions" placeholder="Seleccione primer día" search-placeholder="Buscar día..." :disabled="disabled" /></BioNexusFormField></div>
        </BioNexusSectionPanel>
        <BioNexusSectionPanel title="Presentación monetaria" description="Los símbolos, posiciones y decimales se administran únicamente en el catálogo Monedas." icon="payments" variant="accent">
          <div class="fields-grid fields-grid-three"><BioNexusFormField label="Moneda local" field-id="app-local-currency"><input id="app-local-currency" :value="currencyLabel(localCurrency)" class="bio-nexus-field calculated-field" readonly></BioNexusFormField><BioNexusFormField label="Moneda base" field-id="app-base-currency"><input id="app-base-currency" :value="currencyLabel(baseCurrency)" class="bio-nexus-field calculated-field" readonly></BioNexusFormField><BioNexusFormField label="Visualización financiera principal" field-id="app-financial-primary"><BioNexusSearchableSelect id="app-financial-primary" v-model="model.financial_primary_currency_id" :options="financialCurrencyOptions" value-key="id" label-key="label" placeholder="Seleccione una moneda" search-placeholder="Buscar moneda..." empty-text="Sin monedas activas coincidentes" :disabled="disabled" /></BioNexusFormField><BioNexusFormField label="Separador decimal" field-id="app-decimal-separator"><BioNexusSearchableSelect id="app-decimal-separator" v-model="model.decimal_separator" :options="decimalSeparatorOptions" placeholder="Seleccione separador decimal" search-placeholder="Buscar separador..." :disabled="disabled" /></BioNexusFormField></div>
        </BioNexusSectionPanel>
      </div>
      <BioNexusSectionPanel title="Vista previa" description="Así se mostrará la información con la configuración seleccionada." icon="visibility" variant="soft" class="preview-panel"><div class="preview-list"><div><span>Fecha</span><strong>{{previewDate}}</strong></div><div><span>Fecha y hora</span><strong>{{previewDateTime}}</strong></div><div><span>Número</span><strong>{{previewNumber}}</strong></div><div><span>Precio base</span><strong>{{previewUsd}}</strong></div><div><span>Equivalente local</span><strong>{{previewCurrency}}</strong></div><div><span>Presentación financiera</span><strong>{{previewDual.primary}}</strong><small>{{previewDual.secondary}}</small></div></div><div class="separator-summary"><span><b>Decimal:</b> {{decimalSeparator}}</span><span><b>Miles:</b> {{groupSeparator}}</span><span><b>Semana inicia:</b> {{firstDayLabel}}</span></div></BioNexusSectionPanel>
    </section>

    <section v-show="activeTab==='session'" id="application-settings-panel-session" role="tabpanel" aria-labelledby="application-settings-tab-session">
      <BioNexusSectionPanel title="Duración y control de la sesión" description="La sesión se renueva mientras exista actividad; la inactividad controla el aviso previo al cierre." icon="security" variant="accent">
        <div class="fields-grid fields-grid-three"><BioNexusFormField label="Duración de la sesión" field-id="app-session-timeout" required :error="showErrors?sessionError:''" help="Entre 5 y 1440 minutos."><div class="number-with-unit"><BioNexusNumericInput id="app-session-timeout" v-model="model.session_timeout_minutes" :decimals="0" :max="1440" :disabled="disabled" :invalid="showErrors&&Boolean(sessionError)"/><span>minutos</span></div></BioNexusFormField><BioNexusFormField label="Inactividad" field-id="app-inactivity-timeout" required :error="showErrors?inactivityError:''" help="Entre 1 y 720 minutos."><div class="number-with-unit"><BioNexusNumericInput id="app-inactivity-timeout" v-model="model.inactivity_timeout_minutes" :decimals="0" :max="720" :disabled="disabled" :invalid="showErrors&&Boolean(inactivityError)"/><span>minutos</span></div></BioNexusFormField><BioNexusFormField label="Duración de la cuenta regresiva" field-id="app-countdown" required :error="showErrors?countdownError:''" help="Entre 0 y 600 segundos; 0 deshabilita el diálogo."><div class="number-with-unit"><BioNexusNumericInput id="app-countdown" v-model="model.countdown_seconds" :decimals="0" :max="600" :disabled="disabled" :invalid="showErrors&&Boolean(countdownError)"/><span>segundos</span></div></BioNexusFormField></div><p class="session-rule" :class="{'session-rule-error':showErrors&&Boolean(combinationError)}">{{combinationError||'La inactividad y la cuenta regresiva respetan la duración total de la sesión.'}}</p>
      </BioNexusSectionPanel>
    </section>

    <section v-show="activeTab==='printer'" id="application-settings-panel-printer" role="tabpanel" aria-labelledby="application-settings-tab-printer">
      <BioNexusSectionPanel title="Impresora de toma de muestra" description="Configura el nombre de la impresora y su ubicación de red." icon="print" variant="accent"><div class="fields-grid"><BioNexusFormField label="Impresora tiquera" field-id="app-printer" :help="printerTypeHelp"><input id="app-printer" v-model="model.printer_type" class="bio-nexus-field" maxlength="100" :disabled="disabled"></BioNexusFormField><BioNexusFormField label="Localización en red" field-id="app-interface" :help="printerInterfaceHelp"><input id="app-interface" v-model="model.printer_interface" class="bio-nexus-field" maxlength="100" :disabled="disabled"></BioNexusFormField></div></BioNexusSectionPanel>
    </section>
  </section>
</template>

<script setup>
import{computed}from'vue'
import BioNexusFormField from '@/components/ui/BioNexusFormField.vue'
import BioNexusNumericInput from '@/components/ui/BioNexusNumericInput.vue'
import BioNexusSectionPanel from '@/components/ui/BioNexusSectionPanel.vue'
import BioNexusSearchableSelect from '@/components/ui/BioNexusSearchableSelect.vue'
import{formatDualMoney,formatRegionalMoney,formatRegionalNumber,formatUsdPrice}from'@/services/regionalFormatter'
const props=defineProps({model:{type:Object,required:true},currencies:{type:Array,default:()=>[]},activeTab:{type:String,required:true},disabled:{type:Boolean,default:false},showErrors:{type:Boolean,default:false}})
const selectOption=(value,label)=>({value,label})
const localeOptions=Object.freeze([selectOption('es-VE','Español (Venezuela)')])
const timeZoneOptions=Object.freeze([selectOption('America/Caracas','America/Caracas')])
const dateFormatOptions=Object.freeze([selectOption('dd/MM/yyyy','DD/MM/AAAA'),selectOption('dd-MM-yyyy','DD-MM-AAAA'),selectOption('yyyy-MM-dd','AAAA-MM-DD')])
const hourCycleOptions=Object.freeze([selectOption('h12','12 horas'),selectOption('h23','24 horas')])
const firstDayOptions=Object.freeze([selectOption('monday','Lunes'),selectOption('sunday','Domingo')])
const decimalSeparatorOptions=Object.freeze([selectOption(',','Coma (1.234,56)'),selectOption('.','Punto (1,234.56)')])
const localCurrency=computed(()=>props.currencies.find(x=>x.isLocal&&x.isActive)||null),baseCurrency=computed(()=>props.currencies.find(x=>x.isBase&&x.isActive)||null),activeCurrencies=computed(()=>props.currencies.filter(x=>x.isActive)),financialCurrencyOptions=computed(()=>activeCurrencies.value.map(currency=>({id:Number(currency.id),label:`${currency.name} (${currency.code})`}))),primaryCurrency=computed(()=>props.currencies.find(x=>Number(x.id)===Number(props.model.financial_primary_currency_id))||localCurrency.value)
const sessionError=computed(()=>integerRangeError(props.model.session_timeout_minutes,5,1440,'La duración de la sesión debe estar entre 5 y 1440 minutos.')),inactivityError=computed(()=>integerRangeError(props.model.inactivity_timeout_minutes,1,720,'La inactividad debe estar entre 1 y 720 minutos.')),countdownError=computed(()=>integerRangeError(props.model.countdown_seconds,0,600,'La cuenta regresiva debe estar entre 0 y 600 segundos.'))
const combinationError=computed(()=>{if(sessionError.value||inactivityError.value||countdownError.value)return'';return(Number(props.model.inactivity_timeout_minutes)*60)+Number(props.model.countdown_seconds)>Number(props.model.session_timeout_minutes)*60?'La inactividad más la cuenta regresiva no puede superar la duración de la sesión.':''})
const printerTypeHelp=computed(()=>`${String(props.model.printer_type||'').length} de 100 caracteres`),printerInterfaceHelp=computed(()=>`${String(props.model.printer_interface||'').length} de 100 caracteres. Ej. //localhost/pos-80`)
function integerRangeError(value,min,max,message){const number=Number(value);return!Number.isInteger(number)||number<min||number>max?message:''}function currencyLabel(currency){return currency?`${currency.name} (${currency.code})`:'No configurada'}
const dateParts=computed(()=>{const p={day:'06',month:'09',year:'2026'};if(props.model.date_format==='yyyy-MM-dd')return`${p.year}-${p.month}-${p.day}`;if(props.model.date_format==='dd-MM-yyyy')return`${p.day}-${p.month}-${p.year}`;return`${p.day}/${p.month}/${p.year}`}),previewDate=computed(()=>dateParts.value),previewDateTime=computed(()=>`${dateParts.value}, ${props.model.hour_cycle==='h23'?'20:15':'08:15 p. m.'}`),previewNumber=computed(()=>formatRegionalNumber(1234567.89,props.model,{minimumFractionDigits:2,maximumFractionDigits:2})),decimalSeparator=computed(()=>props.model.decimal_separator==='.'?'.':','),groupSeparator=computed(()=>props.model.decimal_separator==='.'?',':'.'),previewUsd=computed(()=>formatUsdPrice(10,props.model)),previewCurrency=computed(()=>formatRegionalMoney(8375.6,props.model)),previewDual=computed(()=>formatDualMoney(10,837.56,props.model,primaryCurrency.value?.code)),firstDayLabel=computed(()=>props.model.first_day_of_week==='sunday'?'Domingo':'Lunes')
</script>

<style scoped>
.application-settings-panel,.regional-main{display:grid;gap:var(--bio-nexus-space-4)}.regional-layout{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(300px,.75fr);gap:var(--bio-nexus-space-4);align-items:start}.fields-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--bio-nexus-space-3);align-items:start}.fields-grid-three{grid-template-columns:repeat(3,minmax(0,1fr))}.preview-panel{position:sticky;top:calc(var(--bio-nexus-topbar-height) + 78px)}.preview-list{display:grid;gap:var(--bio-nexus-space-2)}.preview-list>div{display:grid;gap:4px;padding:var(--bio-nexus-space-3);border:1px solid var(--bio-nexus-color-border);border-radius:var(--bio-nexus-radius-md);background:var(--bio-nexus-color-surface-soft)}.preview-list span{color:var(--bio-nexus-color-text-muted);font-size:var(--bio-nexus-font-size-xs);font-weight:var(--bio-nexus-font-weight-bold);text-transform:uppercase}.preview-list strong{color:var(--bio-nexus-color-primary-strong);font-size:1.15rem;font-variant-numeric:tabular-nums}.preview-list small{color:var(--bio-nexus-color-text-secondary);font-size:var(--bio-nexus-font-size-sm)}.separator-summary{display:flex;flex-wrap:wrap;gap:var(--bio-nexus-space-3);margin-top:var(--bio-nexus-space-3);padding-top:var(--bio-nexus-space-3);border-top:1px solid var(--bio-nexus-color-border);color:var(--bio-nexus-color-text-secondary);font-size:var(--bio-nexus-font-size-sm)}.calculated-field{background:var(--bio-nexus-color-surface-soft);color:var(--bio-nexus-color-text-secondary);cursor:not-allowed}.number-with-unit{position:relative}.number-with-unit :deep(input){padding-inline-end:76px}.number-with-unit span{position:absolute;inset-inline-end:12px;inset-block-start:50%;transform:translateY(-50%);color:var(--bio-nexus-color-text-muted);font-size:var(--bio-nexus-font-size-xs);pointer-events:none}.session-rule{margin:var(--bio-nexus-space-4) 0 0;padding:var(--bio-nexus-space-3);border:1px solid var(--bio-nexus-color-success-border);border-radius:var(--bio-nexus-radius-md);background:var(--bio-nexus-color-success-soft);color:var(--bio-nexus-color-success-strong)}.session-rule-error{border-color:var(--bio-nexus-color-danger-border);background:var(--bio-nexus-color-danger-soft);color:var(--bio-nexus-color-danger)}@media(max-width:1050px){.regional-layout{grid-template-columns:1fr}.preview-panel{position:static}}@media(max-width:900px){.fields-grid-three{grid-template-columns:1fr}}@media(max-width:800px){.fields-grid{grid-template-columns:1fr}}
</style>