const FALLBACK=Object.freeze({locale:'es-VE',time_zone:'America/Caracas',date_format:'dd/MM/yyyy',hour_cycle:'h12',currency_symbol:'Bs.',currency_symbol_position:'before',financial_primary_currency:'VES',base_currency_symbol:'USD',base_currency_symbol_position:'before',monetary_decimals:2,decimal_separator:','})
function config(value){return{...FALLBACK,...(value&&typeof value==='object'?value:{})}}
function validDate(value){const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?null:date}
function numeric(value){const number=Number(value);return Number.isFinite(number)?number:null}
function dateParts(date,settings){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:settings.time_zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]))}
function dateText(parts,pattern){if(pattern==='yyyy-MM-dd')return parts.year+'-'+parts.month+'-'+parts.day;if(pattern==='dd-MM-yyyy')return parts.day+'-'+parts.month+'-'+parts.year;return parts.day+'/'+parts.month+'/'+parts.year}
export function formatRegionalFunctionalDate(value,regionalSettings={}){const match=String(value??'').match(/^(\d{4})-(\d{2})-(\d{2})/);if(!match)return String(value??'');return dateText({year:match[1],month:match[2],day:match[3]},config(regionalSettings).date_format)}
export function formatRegionalDate(value,regionalSettings={}){const date=validDate(value);if(!date)return'';const settings=config(regionalSettings);return dateText(dateParts(date,settings),settings.date_format)}
export function formatRegionalTime(value,regionalSettings={}){const date=validDate(value);if(!date)return'';const settings=config(regionalSettings);return new Intl.DateTimeFormat(settings.locale,{timeZone:settings.time_zone,hour:'2-digit',minute:'2-digit',hour12:settings.hour_cycle==='h12'}).format(date)}
export function formatRegionalDateTime(value,regionalSettings={}){const date=validDate(value);if(!date)return'';return formatRegionalDate(date,regionalSettings)+', '+formatRegionalTime(date,regionalSettings)}
export function formatRegionalNumber(value,regionalSettings={},options={}){const number=numeric(value);if(number===null)return'';const settings=config(regionalSettings);const formatted=new Intl.NumberFormat(settings.locale,options).format(number);if(settings.decimal_separator===',')return formatted;return formatted.replace(/\./g,'#').replace(/,/g,'.').replace(/#/g,',')}
export function formatRegionalMoney(value,regionalSettings={}){const number=numeric(value);if(number===null)return'';const settings=config(regionalSettings),digits=Number.isInteger(Number(settings.monetary_decimals))?Number(settings.monetary_decimals):2,amount=formatRegionalNumber(number,settings,{minimumFractionDigits:digits,maximumFractionDigits:digits});return settings.currency_symbol_position==='after'?amount+' '+settings.currency_symbol:settings.currency_symbol+' '+amount}
export function formatUsdPrice(value,regionalSettings={}){const number=numeric(value);if(number===null)return'';const settings=config(regionalSettings),digits=Number.isInteger(Number(settings.monetary_decimals))?Number(settings.monetary_decimals):2,amount=formatRegionalNumber(number,settings,{minimumFractionDigits:digits,maximumFractionDigits:digits});return settings.base_currency_symbol_position==='after'?amount+' '+settings.base_currency_symbol:settings.base_currency_symbol+' '+amount}
export function convertUsdToLocal(value,exchangeRate){const amount=numeric(value),rate=numeric(exchangeRate);return amount===null||rate===null||rate<=0?null:Math.round((amount*rate+Number.EPSILON)*100)/100}
export function formatLocalMoney(value,regionalSettings={}){return formatRegionalMoney(value,regionalSettings)}
export function formatDualMoney(valueUsd,exchangeRate,regionalSettings={},primaryCurrency=regionalSettings.financial_primary_currency||'VES'){const usd=formatUsdPrice(valueUsd,regionalSettings),localValue=convertUsdToLocal(valueUsd,exchangeRate),local=localValue===null?'':formatLocalMoney(localValue,regionalSettings);return primaryCurrency==='USD'?{primary:usd,secondary:local,usd,local}:{primary:local||usd,secondary:local?usd:'',usd,local}}
export function formatRegionalAmount(value,regionalSettings={}){const settings=config(regionalSettings),digits=Number.isInteger(Number(settings.monetary_decimals))?Number(settings.monetary_decimals):2;return formatRegionalNumber(value,settings,{minimumFractionDigits:digits,maximumFractionDigits:digits})}

export function parseRegionalNumber(value,regionalSettings={}){const settings=config(regionalSettings),text=String(value??'').trim();if(!text)return null;const decimal=settings.decimal_separator===','?',':'.',group=decimal===','?'.':',';const normalized=text.split(group).join('').replace(decimal,'.');if(!/^[+-]?(?:\d+|\d*\.\d+)$/.test(normalized))return null;const number=Number(normalized);return Number.isFinite(number)?number:null}
