import {apiRequest} from '@/api/apiClient'
import {normalizeSpecialTestItem,normalizeSpecialTestLab,normalizeSpecialTestLabs,normalizeSpecialTestLabPayload,normalizeSpecialTestItemPayload} from '@/models/specialTests'
const LAB='/api/specialtestlab',ITEM='/api/specialtestItems'
export async function getSpecialTestLabs(){return normalizeSpecialTestLabs(await apiRequest(LAB))}
export async function getSpecialTestLab(id){return normalizeSpecialTestLab(await apiRequest(LAB+'/'+id))}
export async function createSpecialTestLab(values){return normalizeSpecialTestLab(await apiRequest(LAB,{method:'POST',body:normalizeSpecialTestLabPayload(values)}))}
export async function updateSpecialTestLab(id,changes){return normalizeSpecialTestLab(await apiRequest(LAB+'/'+id,{method:'PATCH',body:changes}))}
export async function createSpecialTestItem(values){return normalizeSpecialTestItem(await apiRequest(ITEM,{method:'POST',body:normalizeSpecialTestItemPayload(values)}))}
export async function updateSpecialTestItem(id,values){return normalizeSpecialTestItem(await apiRequest(ITEM+'/'+id,{method:'PATCH',body:normalizeSpecialTestItemPayload(values)}))}
export async function deleteSpecialTestItem(id){return apiRequest(ITEM+'/'+id,{method:'DELETE'})}
export function specialTestsError(error,fallback){const m={SPECIAL_TEST_NOT_FOUND:'El laboratorio ya no existe.',SPECIAL_TEST_UPDATE_REQUIRED:'No existen cambios para guardar.',SPECIAL_TEST_DESCRIPTION_ALREADY_EXISTS:'Ya existe un laboratorio de referencia con ese nombre.',SPECIAL_TEST_EXAMS_REQUIRED:'Selecciona al menos un examen.',SPECIAL_TEST_DESCRIPTION_REQUIRED:'La descripcion es obligatoria.',SPECIAL_TEST_DESCRIPTION_TOO_LONG:'La descripcion supera el limite permitido.',SPECIAL_TEST_ADDRESS_TOO_LONG:'La direccion supera el limite permitido.',SPECIAL_TEST_PHONE_1_INVALID:'El telefono principal no es valido.',SPECIAL_TEST_PHONE_2_INVALID:'El telefono alterno no es valido.',SPECIAL_TEST_EMAIL_INVALID:'El correo electronico no es valido.',SPECIAL_TEST_PERMISSION_REQUIRED:'La cuenta no tiene permiso para realizar esta operacion.',SPECIAL_TEST_ITEM_NOT_FOUND:'La prueba asociada ya no existe.',SPECIAL_TEST_ITEM_ALREADY_EXISTS:'El examen ya pertenece a este laboratorio.',SPECIAL_TEST_EXAM_NOT_FOUND:'El examen seleccionado ya no existe.',SPECIAL_TEST_ITEM_DESCRIPTION_REQUIRED:'La descripcion de la prueba es obligatoria.',SPECIAL_TEST_ITEM_DESCRIPTION_TOO_LONG:'La descripcion de la prueba supera 60 caracteres.'};return m[error?.message]||error?.message||fallback}
