<template>
  <section class="exam-order-page">
    <header class="exam-order-toolbar">
      <div><p>CATÁLOGOS</p><h1>Ordenar exámenes</h1><span>Organiza grupos y exámenes sin alterar sus datos.</span></div>
      <div class="exam-order-actions"><button class="bio-nexus-button secondary" :disabled="!dirty || saving" @click="discard">Descartar</button><button class="bio-nexus-button primary" :disabled="!dirty || !canUpdate || saving" @click="save">{{ saving ? "Guardando..." : "Guardar orden" }}</button></div>
    </header>
    <p v-if="error" class="exam-order-error">{{ error }}</p>
    <div v-if="loading" class="exam-order-state">Cargando catálogo...</div>
    <div v-else class="exam-order-layout">
      <article class="exam-order-panel"><header><div><small>ORDEN GLOBAL</small><h2>Grupos de exámenes</h2></div><span>{{ groups.length }} grupo(s)</span></header>
        <ol class="exam-order-list"><li v-for="(group,index) in groups" :key="group.id" :class="{selected:group.id===selectedGroupId,inactive:group.annulled}"><button class="select-row" @click="selectedGroupId=group.id"><span class="drag-icon">⋮⋮</span><span><strong>{{ group.description }}</strong><small>{{ group.annulled ? "Inactivo" : "Activo" }}</small></span></button><div class="move-actions"><button :disabled="index===0 || saving" aria-label="Subir grupo" @click="move(groups,index,-1)">↑</button><button :disabled="index===groups.length-1 || saving" aria-label="Bajar grupo" @click="move(groups,index,1)">↓</button></div></li></ol>
      </article>
      <article class="exam-order-panel"><header><div><small>ORDEN DEL GRUPO</small><h2>{{ selectedGroup?.description || "Exámenes" }}</h2></div><span>{{ exams.length }} examen(es)</span></header>
        <div v-if="!selectedGroup" class="exam-order-state">Selecciona un grupo.</div><ol v-else class="exam-order-list"><li v-for="(exam,index) in exams" :key="exam.id" :class="{inactive:exam.annulled}"><div class="select-row static"><span class="drag-icon">⋮⋮</span><span><strong>{{ exam.description }}</strong><small>{{ exam.abbreviation }} · {{ exam.annulled ? "Inactivo" : "Activo" }}</small></span></div><div class="move-actions"><button :disabled="index===0 || saving" aria-label="Subir examen" @click="move(exams,index,-1)">↑</button><button :disabled="index===exams.length-1 || saving" aria-label="Bajar examen" @click="move(exams,index,1)">↓</button></div></li></ol>
      </article>
    </div>
  </section>
</template>
<script setup>
import { computed,onBeforeUnmount,onMounted,ref,watch } from "vue";
import { onBeforeRouteLeave } from "vue-router";
import { useSessionStore } from "@/stores/session";
import { useBioNexusToast } from "@/composables/useBioNexusToast";
import { examCatalogError,getExamGroups,getExamsByGroup,reorderExamGroups,reorderExams } from "@/services/examCatalogService";
const session=useSessionStore(),toast=useBioNexusToast(),groups=ref([]),examsByGroup=ref({}),selectedGroupId=ref(null),loading=ref(true),saving=ref(false),error=ref(""),original=ref("");
const selectedGroup=computed(()=>groups.value.find(x=>x.id===selectedGroupId.value)||null),exams=computed(()=>examsByGroup.value[selectedGroupId.value]||[]),snapshot=()=>JSON.stringify({groups:groups.value.map(x=>x.id),exams:Object.fromEntries(groups.value.map(g=>[g.id,(examsByGroup.value[g.id]||[]).map(x=>x.id)]))}),dirty=computed(()=>!loading.value&&snapshot()!==original.value),canUpdate=computed(()=>session.hasPermission?.("exam-catalog.update")??false);
function move(list,index,delta){const target=index+delta;if(target<0||target>=list.length)return;const [row]=list.splice(index,1);list.splice(target,0,row)}
async function load(){loading.value=true;error.value="";try{groups.value=await getExamGroups();const entries=await Promise.all(groups.value.map(async g=>[g.id,await getExamsByGroup(g.id)]));examsByGroup.value=Object.fromEntries(entries);selectedGroupId.value=groups.value[0]?.id||null;original.value=snapshot()}catch(e){error.value=examCatalogError(e,"No fue posible cargar el orden de exámenes.");toast.error(error.value)}finally{loading.value=false}}
async function save(){if(!dirty.value||!canUpdate.value||saving.value)return;saving.value=true;error.value="";try{const before=JSON.parse(original.value),current=JSON.parse(snapshot());if(JSON.stringify(before.groups)!==JSON.stringify(current.groups))await reorderExamGroups(current.groups);for(const group of groups.value){if(JSON.stringify(before.exams[group.id])!==JSON.stringify(current.exams[group.id]))await reorderExams(group.id,current.exams[group.id])}toast.success("Orden guardado correctamente.");await load()}catch(e){error.value=examCatalogError(e,"No fue posible guardar el orden.");toast.error(error.value);await load()}finally{saving.value=false}}
function discard(){const value=JSON.parse(original.value),byGroup=new Map(groups.value.map(x=>[x.id,x])),examMaps=Object.fromEntries(Object.entries(examsByGroup.value).map(([id,rows])=>[id,new Map(rows.map(x=>[x.id,x]))]));groups.value=value.groups.map(id=>byGroup.get(id)).filter(Boolean);examsByGroup.value=Object.fromEntries(Object.entries(value.exams).map(([id,ids])=>[id,ids.map(x=>examMaps[id]?.get(x)).filter(Boolean)]))}
function guard(event){if(dirty.value){event.preventDefault();event.returnValue=""}}onBeforeRouteLeave(()=>!dirty.value||globalThis.confirm("Hay cambios de orden sin guardar. ¿Deseas salir y descartarlos?"));watch(selectedGroupId,()=>{error.value=""});onMounted(()=>{globalThis.addEventListener("beforeunload",guard);load()});onBeforeUnmount(()=>globalThis.removeEventListener("beforeunload",guard));
</script>
<style scoped>
.exam-order-page{display:grid;gap:var(--bio-nexus-space-4);min-width:0}.exam-order-toolbar{position:sticky;z-index:15;top:calc(var(--bio-nexus-topbar-height) + var(--bio-nexus-space-2));display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 18px;border:1px solid var(--bio-nexus-color-border);border-radius:var(--bio-nexus-radius-md);background:var(--bio-nexus-color-surface);box-shadow:var(--bio-nexus-shadow-sm)}h1,h2,p{margin:0}.exam-order-toolbar p,.exam-order-panel small{color:var(--bio-nexus-color-accent);font-size:11px;font-weight:800}.exam-order-toolbar span,.exam-order-list small{color:var(--bio-nexus-color-text-muted)}.exam-order-actions{display:flex;gap:8px}.exam-order-layout{display:grid;grid-template-columns:minmax(280px,.9fr) minmax(360px,1.1fr);gap:16px}.exam-order-panel{min-width:0;padding:16px;border:1px solid var(--bio-nexus-color-border);border-radius:var(--bio-nexus-radius-md);background:var(--bio-nexus-color-surface)}.exam-order-panel>header{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.exam-order-list{display:grid;gap:6px;margin:0;padding:0;list-style:none}.exam-order-list li{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;border:1px solid var(--bio-nexus-color-border);border-radius:var(--bio-nexus-radius-md);background:var(--bio-nexus-color-surface-soft)}.exam-order-list li.selected{border-color:var(--bio-nexus-color-primary);box-shadow:inset 3px 0 0 var(--bio-nexus-color-accent)}.exam-order-list li.inactive{opacity:.65}.select-row{display:flex;align-items:center;gap:10px;min-width:0;padding:10px;border:0;background:transparent;text-align:left;cursor:pointer}.select-row.static{cursor:default}.select-row>span:not(.drag-icon){display:grid;min-width:0}.select-row strong,.select-row small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.drag-icon{color:var(--bio-nexus-color-primary);font-weight:900}.move-actions{display:flex;gap:4px;padding-right:8px}.move-actions button{display:grid;place-items:center;width:32px;height:32px;border:1px solid var(--bio-nexus-color-border);border-radius:50%;background:var(--bio-nexus-color-surface);color:var(--bio-nexus-color-primary);cursor:pointer}.move-actions button:disabled{opacity:.35;cursor:not-allowed}.exam-order-state{padding:24px;text-align:center;color:var(--bio-nexus-color-text-muted)}.exam-order-error{padding:10px;border-radius:var(--bio-nexus-radius-md);background:var(--bio-nexus-color-danger-soft);color:var(--bio-nexus-color-danger)}@media(max-width:900px){.exam-order-layout{grid-template-columns:1fr}.exam-order-toolbar{position:static;align-items:stretch;flex-direction:column}.exam-order-actions{justify-content:flex-end}}
</style>
