export const navigationItems = [
  {
    key: "dashboard",
    label: "Inicio",
    abbreviation: "IN",
    routeName: "dashboard",
    legacyRouteName: "home",
    roles: ["user", "admin"],
    migrated: true,
  },
  {
    key: "history",
    label: "Historia",
    abbreviation: "HI",
    legacyRouteName: "PatientHistory",
    roles: ["user", "admin"],
    migrated: false,
  },
  {
    key: "daily-routine",
    label: "Rutina diaria",
    abbreviation: "RD",
    roles: ["user", "admin"],
    children: [
      {
        key: "patient-admission",
        label: "Ingreso de pacientes",
        abbreviation: "IP",
        legacyRouteName: "PatientAdmission",
        legacyPath: "/admission",
        roles: ["user", "admin"],
        migrated: false,
      },
      {
        key: "worksheet",
        label: "Hoja de trabajo",
        abbreviation: "HT",
        legacyRouteName: "Worksheet",
        legacyPath: "/worksheet",
        roles: ["user", "admin"],
        migrated: false,
      },
      {
        key: "patient-approve",
        label: "Aprobar resultados",
        abbreviation: "AR",
        legacyRouteName: "PatientApprove",
        legacyPath: "/approve",
        roles: ["user", "admin"],
        migrated: false,
      },
      {
        key: "results-email",
        label: "Entrega de resultados por email",
        abbreviation: "CE",
        legacyRouteName: "ResultsByEmail",
        legacyPath: "/email",
        roles: ["user", "admin"],
        migrated: false,
      },
      {
        key: "special-test-results",
        label: "Pruebas especiales",
        abbreviation: "PE",
        legacyRouteName: "SpecialTestResults",
        legacyPath: "/special",
        roles: ["user", "admin"],
        migrated: false,
      },
    ],
  },
  {
    key: "movements",
    label: "Movimientos",
    abbreviation: "MO",
    roles: ["admin"],
    children: [
      {
        key: "cash",
        label: "Caja",
        abbreviation: "CA",
        legacyRouteName: "Cash",
        legacyPath: "/movements/cash",
        roles: ["admin"],
        migrated: false,
      },
      {
        key: "movement-consultation",
        label: "Consultas",
        abbreviation: "CM",
        legacyRouteName: "consultation",
        legacyPath: "/movements/consultation",
        roles: ["admin"],
        migrated: false,
      },
      {
        key: "accounts-receivable",
        label: "Cuentas por cobrar",
        abbreviation: "CC",
        legacyRouteName: "accountsReceivable",
        legacyPath: "/movements/accounts-receivable",
        roles: ["admin"],
        migrated: false,
      },
      {
        key: "cancel-accounts-receivable",
        label: "Cancelacion de cuentas por cobrar",
        abbreviation: "CX",
        legacyRouteName: "cancelAccountsReceivable",
        legacyPath: "/movements/cancelinvoice",
        roles: ["admin"],
        migrated: false,
      },
      {
        key: "issued-invoices",
        label: "Facturas emitidas",
        abbreviation: "FE",
        legacyRouteName: "issuedInvoices",
        legacyPath: "/movements/invoice",
        roles: ["admin"],
        migrated: false,
      },
      {
        key: "registered-customers",
        label: "Clientes registrados",
        abbreviation: "CR",
        legacyRouteName: "registeredCustomers",
        legacyPath: "/movements/customers",
        roles: ["admin"],
        migrated: false,
      },
    ],
  },
  {
    key: "settings",
    label: "Configuración",
    abbreviation: "CO",
    children: [
      { key: "configuration-catalogs", label: "Catálogos", abbreviation: "CA", routeName: "configuration-catalogs", migrated: true },
      { key: "configuration-laboratory", label: "Laboratorio", abbreviation: "LA", routeName: "configuration-laboratory-module", permissions: ["laboratory.read"], migrated: true },
      { key: "configuration-patient-care", label: "Atención al paciente", abbreviation: "AP", routeName: "configuration-patient-care", migrated: true },
      { key: "configuration-sampling", label: "Toma de muestras", abbreviation: "TM", routeName: "configuration-sampling", migrated: true },
      { key: "configuration-billing", label: "Facturación", abbreviation: "FA", routeName: "configuration-billing-module", migrated: true },
      { key: "configuration-documents", label: "Documentos y plantillas", abbreviation: "DP", routeName: "configuration-documents", migrated: true },
      { key: "configuration-system", label: "Sistema", abbreviation: "SI", routeName: "configuration-system-module", permissions: ["application-settings.read"], migrated: true },
      { key: "configuration-security", label: "Seguridad", abbreviation: "SE", routeName: "configuration-security-module", permissions: ["security.roles.read", "security.permissions.read", "security.users.read"], migrated: true }
    ]
  },
  {
    key: "about",
    label: "Acerca de",
    abbreviation: "AC",
    legacyRouteName: "about",
    legacyPath: "/about",
    roles: ["user", "admin"],
    migrated: false,
  },
  ];
