import fs from "node:fs";
import assert from "node:assert/strict";
const read = path => fs.readFileSync(path, "utf8");
const router = read("src/router/index.js");
const breadcrumb = read("src/components/layout/AppBreadcrumb.vue");
const view = read("src/views/TaxesView.vue");
const dialog = read("src/components/tax/TaxDialog.vue");
const state = read("src/components/tax/TaxStateDialog.vue");
const service = read("src/services/taxService.js");
const configuration = "Configuraci" + String.fromCodePoint(243) + "n";
const billing = "Facturaci" + String.fromCodePoint(243) + "n";
const updateStart = service.indexOf("export async function updateTax(");
const updateEnd = service.indexOf("export function getTaxErrorMessage", updateStart);
assert.ok(updateStart >= 0 && updateEnd > updateStart, "UPDATE_TAX_NOT_FOUND");
const update = service.slice(updateStart, updateEnd);
for (const value of [configuration, billing, "Impuestos"]) assert.ok(router.includes(value), "BREADCRUMB_" + value);
assert.ok(breadcrumb.includes('name: "configuration-billing-module"') && breadcrumb.includes(billing), "BILLING_LINK");
assert.ok(/colId\s*:\s*["']isActive["']/.test(view), "ACTIVE_COLUMN");
assert.ok(/valueGetter\s*:\s*\([^)]*\)\s*=>\s*!\s*[^,;\n]*hide/.test(view), "ACTIVE_SEMANTICS");
assert.ok(/onLabel\s*:\s*["']Activo["']/.test(view), "ACTIVE_ON");
assert.ok(/offLabel\s*:\s*["']Inactivo["']/.test(view), "INACTIVE_OFF");
assert.ok(/mode\.value\s*===?\s*["']create["'][^:]*\?\s*!?props\.canCreate/.test(dialog), "CREATE_PERMISSION");
assert.ok(/attempted\.value\s*=\s*true/.test(dialog), "VALIDATE_ON_CLICK");
assert.ok(dialog.includes("descriptionError") && dialog.includes("valueError"), "FIELD_ERRORS");
assert.ok(/!\s*dirty\.value/.test(dialog), "EDIT_DIRTY");
assert.ok(/hasOwnProperty\.call\(source\s*,\s*field\)/.test(update), "PARTIAL_PATCH");
assert.ok(!/body\s*:\s*changes\(value\)/.test(update), "FULL_PATCH");
assert.ok(state.includes("BioNexusStateDialog"), "STATE_DIALOG");
assert.ok(/updateTax\(row\.id\s*,\s*\{\s*hide\s*:\s*!\s*row\.hide\s*\}\s*\)/.test(view), "STATE_ONLY_HIDE");
assert.ok(!view.includes("TaxDeleteDialog") && !service.includes('method:"DELETE"'), "NO_DELETE");
console.log("Tax visual semantic contract approved.");
