import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
const dialog=fs.readFileSync("src/components/security/UserIdentityDialog.vue","utf8");
test("las cuatro agrupaciones semanticas tienen SectionPanel",()=>{for(const title of ["Datos de identidad","Acceso","Archivos de identidad","Clave de firma"])assert.ok(dialog.includes(`title="${title}"`),title);assert.equal((dialog.match(/class="identity-section-panel/g)||[]).length,4);});
test("Datos de identidad contiene los siete campos ordinarios",()=>{const start=dialog.indexOf('title="Datos de identidad"');const end=dialog.indexOf('</BioNexusSectionPanel>',start);const block=dialog.slice(start,end);for(const id of ["identity-name","identity-user-name","identity-email","identity-telephone","identity-position","identity-college","identity-direction"])assert.ok(block.includes(`field-id="${id}"`),id);});
test("Archivos contiene fotografia y firma debajo del encabezado",()=>{const start=dialog.indexOf('title="Archivos de identidad"');const end=dialog.indexOf('</BioNexusSectionPanel>',start);const block=dialog.slice(start,end);assert.ok(block.includes('<div class="identity-media-section">'));assert.equal((block.match(/<article class="identity-media-card">/g)||[]).length,2);assert.ok(block.includes("Seleccionar fotografia"));assert.ok(block.includes("Seleccionar firma"));});
test("el formulario separa uniformemente los paneles",()=>{assert.ok(dialog.includes('.user-identity-form { display: grid; gap: var(--bio-nexus-space-4); min-width: 0; }'));assert.ok(dialog.includes('.identity-section-panel { min-width: 0; margin: 0; }'));});
test("se conservan contratos funcionales",()=>{assert.equal((dialog.match(/:error="errors\./g)||[]).length,11);assert.equal((dialog.match(/<BioNexusActionButton/g)||[]).length,4);for(const token of ['identitySubmitDisabled','validateRemoteEmail','uploadUserAsset','selectPhoto','selectSignature'])assert.ok(dialog.includes(token),token);});
