import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
const dialog=fs.readFileSync("src/components/security/UserDetailDialog.vue","utf8");
test("usa cuatro SectionPanel accent con separacion uniforme",()=>{for(const title of ["Estado y acceso","Datos de identidad","Roles y permisos","Archivos de identidad"])assert.ok(dialog.includes(`title="${title}"`),title);assert.equal((dialog.match(/<BioNexusSectionPanel/g)||[]).length,4);assert.equal((dialog.match(/variant="accent" compact/g)||[]).length,4);assert.ok(dialog.includes('.user-detail-content { display: grid; gap: var(--bio-nexus-space-4); }'));});
test("cada bloque conserva sus datos",()=>{const block=(title)=>{const start=dialog.indexOf(`title="${title}"`);const end=dialog.indexOf('</BioNexusSectionPanel>',start);return dialog.slice(start,end);};for(const token of ["userName","user.name","user.position","user.hidden"])assert.ok(block("Estado y acceso").includes(token),token);for(const token of ["user.email","user.telephone","user.collegeNumber"])assert.ok(block("Datos de identidad").includes(token),token);for(const token of ["assignedRoles","inheritedPermissions","permissionOverrides","context.roles","context.permissions","deniedPermissions"])assert.ok(block("Roles y permisos").includes(token),token);for(const token of ["user.photo","user.signature","Fotografia","Firma digital"])assert.ok(block("Archivos de identidad").includes(token),token);});
test("permanece estrictamente de solo lectura",()=>{assert.equal(dialog.includes('v-model'),false);assert.equal((dialog.match(/<input\b|<textarea\b|<select\b/g)||[]).length,0);assert.equal(dialog.includes('@click="close"'),true);});
test("usa accion compartida y elimina boton nativo",()=>{assert.ok(dialog.includes('<BioNexusActionButton type="button" variant="secondary" icon="close" @click="close">Cerrar</BioNexusActionButton>'));assert.equal((dialog.match(/<button\b/g)||[]).length,0);});
test("preserva estados, imagenes, dialogo y API publica",()=>{for(const token of ['v-if="loading"','v-else-if="errorMessage"','v-else-if="authorization"','assetUrl','/api/public/','defineExpose({ open, close })'])assert.ok(dialog.includes(token),token);});
