<template>
  <BioNexusDialog ref="box" size="standard" :kicker="mode === 'create' ? 'Nuevo registro' : 'Editar registro'" :title="mode === 'create' ? 'Crear impuesto' : 'Editar impuesto'" :prevent-close="saving || dirty" @before-close="requestClose" @close="handleClosed">
    <section class="tax-dialog-body">
      <BioNexusFormErrors :errors="errorMessage" />
      <BioNexusSectionPanel title="Información del impuesto" icon="percent" description="Define la descripción, el porcentaje y las reglas de aplicación." variant="accent">
        <div class="tax-form-grid">
          <BioNexusFormField label="Descripción" field-id="tax-description" :error="descriptionError" :help="draft.description.length + ' de 20 caracteres'" required><input id="tax-description" ref="firstInput" v-model="draft.description" class="bio-nexus-field" maxlength="20" autocomplete="off" :disabled="saving" @input="syncDirty"></BioNexusFormField>
          <BioNexusFormField label="Porcentaje" field-id="tax-value" :error="valueError" required><BioNexusNumericInput id="tax-value" v-model="draft.value" :min="0" :max="100" :disabled="saving" :invalid="Boolean(valueError)" @input="syncDirty" /></BioNexusFormField>
          <div class="tax-options"><BioNexusCheckbox v-model="draft.only_dollars" label="Solo dólares" :disabled="saving" @change="syncDirty" /><BioNexusCheckbox v-model="draft.always_subtotal" label="Fijo en subtotal" :disabled="saving" @change="syncDirty" /></div>
        </div>
      </BioNexusSectionPanel>
    </section>
    <template #footer><BioNexusActionButton variant="secondary" icon="cancel" :disabled="saving" @click="requestClose">Cancelar</BioNexusActionButton><BioNexusActionButton variant="primary" icon="save" :loading="saving" :disabled="submitDisabled" @click="submit">{{ mode === 'create' ? 'Crear' : 'Guardar' }}</BioNexusActionButton></template>
  </BioNexusDialog>
  <BioNexusConfirmDialog ref="discardDialog" />
</template>
<script setup>
import { computed, nextTick, reactive, ref } from "vue";
import BioNexusActionButton from "@/components/ui/BioNexusActionButton.vue";
import BioNexusCheckbox from "@/components/ui/BioNexusCheckbox.vue";
import BioNexusConfirmDialog from "@/components/ui/BioNexusConfirmDialog.vue";
import BioNexusDialog from "@/components/ui/BioNexusDialog.vue";
import BioNexusFormErrors from "@/components/ui/BioNexusFormErrors.vue";
import BioNexusFormField from "@/components/ui/BioNexusFormField.vue";
import BioNexusNumericInput from "@/components/ui/BioNexusNumericInput.vue";
import BioNexusSectionPanel from "@/components/ui/BioNexusSectionPanel.vue";
import { formatRegionalNumber } from "@/services/regionalFormatter";
import { useRegionalSettingsStore } from "@/stores/regionalSettings";
const props=defineProps({saving:Boolean,canCreate:Boolean,canUpdate:Boolean,taxes:{type:Array,default:()=>[]}}),emit=defineEmits(["submit"]),settings=useRegionalSettingsStore(),box=ref(null),discardDialog=ref(null),firstInput=ref(null),mode=ref("create"),current=ref(null),attempted=ref(false),errorMessage=ref(""),original=ref(""),dirty=ref(false),draft=reactive({description:"",value:0,only_dollars:false,always_subtotal:false});
const numericValue=computed(()=>Number.isFinite(Number(draft.value))?Number(draft.value):null),values=computed(()=>({description:draft.description.trim(),value:numericValue.value,only_dollars:Boolean(draft.only_dollars),always_subtotal:Boolean(draft.always_subtotal)})),signature=computed(()=>JSON.stringify(values.value)),percentagePlaceholder=computed(()=>"0"+settings.settings.decimal_separator+"00"),normalizedDescription=computed(()=>values.value.description.toLocaleLowerCase()),descriptionDuplicate=computed(()=>Boolean(normalizedDescription.value)&&props.taxes.some(row=>Number(row?.id)!==Number(current.value?.id)&&String(row?.description||"").trim().toLocaleLowerCase()===normalizedDescription.value)),descriptionError=computed(()=>attempted.value&&!values.value.description?"La descripción es obligatoria.":""),valueError=computed(()=>attempted.value&&(numericValue.value===null||numericValue.value<0||numericValue.value>100)?"Use un porcentaje entre 0 y 100 con separador "+settings.settings.decimal_separator+".":""),isValid=computed(()=>Boolean(values.value.description)&&numericValue.value!==null&&numericValue.value>=0&&numericValue.value<=100),submitDisabled=computed(()=>props.saving||(mode.value==="create"?(!props.canCreate||!dirty.value||!isValid.value):(!props.canUpdate||!dirty.value||!isValid.value)));
function display(v){const digits=Number(settings.settings.monetary_decimals)||0;return Number(formatRegionalNumber(v,settings.settings,{minimumFractionDigits:digits,maximumFractionDigits:digits}).replace(/[^0-9,-.]/g,""))||Number(v)||0}function syncDirty(){dirty.value=signature.value!==original.value;if(errorMessage.value)errorMessage.value=""}function assign(row){draft.description=row?.description||"";draft.value=Number(row?.value)||0;draft.only_dollars=Boolean(row?.only_dollars);draft.always_subtotal=Boolean(row?.always_subtotal)}async function show(){await box.value?.open();await nextTick();original.value=signature.value;dirty.value=false;firstInput.value?.focus()}async function openCreate(){mode.value="create";current.value=null;assign(null);attempted.value=false;errorMessage.value="";await show()}async function openEdit(row){mode.value="edit";current.value=row;assign(row);attempted.value=false;errorMessage.value="";await show()}async function requestClose(){if(props.saving)return;if(dirty.value){const accepted=await discardDialog.value?.ask({title:"Descartar cambios",message:"Hay cambios sin guardar. ¿Deseas salir y descartarlos?",confirmText:"Sí, salir y descartar cambios",confirmIcon:"delete",variant:"danger"});if(!accepted)return}box.value?.close()}function close(){box.value?.close()}function handleClosed(){attempted.value=false;errorMessage.value="";dirty.value=false}function setError(v){errorMessage.value=String(v||"")}function clearError(){errorMessage.value=""}function markSaved(row){current.value=row;assign(row);original.value=signature.value;dirty.value=false;attempted.value=false;errorMessage.value=""}function submit(){attempted.value=true;if(descriptionError.value||valueError.value||submitDisabled.value)return;emit("submit",{mode:mode.value,record:current.value,values:values.value})}defineExpose({openCreate,openEdit,close,requestClose,setError,clearError,markSaved});
</script>
<style scoped>.tax-dialog-body{display:grid;gap:var(--bio-nexus-space-3)}.tax-form-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(150px,1fr);gap:var(--bio-nexus-space-3);align-items:start}.tax-options{grid-column:1/-1;display:flex;gap:var(--bio-nexus-space-4);flex-wrap:wrap}@media(max-width:620px){.tax-form-grid{grid-template-columns:1fr}}</style>
