<template>
  <BioNexusDialog ref="dialog" size="wide" dialog-class="worksheet-entry-dialog" shell-class="worksheet-entry-shell" body-class="worksheet-entry-body" :prevent-close="saving || changed" :kicker="mode==='create'?'Nuevo registro':'Editar registro'" :title="mode==='create'?'Crear grupo de hoja de trabajo':'Editar grupo de hoja de trabajo'" @before-close="requestClose" @close="reset">
    <BioNexusFormLayout>
      <BioNexusFormErrors :errors="errorMessage" />
      <section class="worksheet-body">
      <div class="worksheet-fields"><BioNexusFormField label="Descripción" field-id="wg-description" :error="descriptionError" :help="draft.description.length + ' de 50 caracteres'" required><input id="wg-description" ref="firstInput" v-model="draft.description" class="bio-nexus-field" maxlength="50" @input="syncDirty"></BioNexusFormField><BioNexusFormField label="Detalles" field-id="wg-details" :help="draft.details.length+' de 200 caracteres'"><textarea id="wg-details" v-model="draft.details" class="bio-nexus-field" maxlength="200" rows="2" @input="syncDirty"></textarea></BioNexusFormField></div>
      <div class="worksheet-picker"><section class="worksheet-panel"><BioNexusFormField label="Buscar examen" field-id="wg-search"><input id="wg-search" v-model="search" class="bio-nexus-field" type="search" autocomplete="off"></BioNexusFormField><div class="worksheet-list"><article v-for="exam in available" :key="exam.id" class="worksheet-row"><span class="catalog-mark">+</span><span class="row-copy"><strong>{{exam.description}}</strong><small>{{exam.abbreviation||'Sin abreviatura'}}</small></span><div class="available-actions"><BioNexusActionButton size="sm" variant="secondary" icon="visibility" icon-only shape="circle" label="Detalle" @click="openDetail(exam)" /><BioNexusActionButton size="sm" variant="primary" icon="add" icon-only shape="circle" label="Agregar" :disabled="!canManageItems" @click="add(exam)" /></div></article><p v-if="!available.length" class="worksheet-empty">No hay exámenes disponibles.</p></div></section>
      <section class="worksheet-panel"><header><strong>Exámenes seleccionados</strong><span>{{draft.items.length}}</span></header><p v-if="attempted&&!draft.items.length" class="worksheet-error">Selecciona al menos un examen.</p><div class="worksheet-list"><article v-for="(item,index) in draft.items" :key="item.examId" class="worksheet-row"><span class="order-number">{{index+1}}</span><span class="row-copy"><strong>{{item.description}}</strong><small>{{item.abbreviation||'Examen de catálogo'}}</small></span><button type="button" class="remove" :disabled="!canManageItems" @click="remove(index)">Quitar</button></article></div></section></div>
    </section>
    </BioNexusFormLayout>
    <template #footer><button class="bio-nexus-action bio-nexus-action-secondary" :disabled="saving" @click="requestClose"><BioNexusActionIcon action="cancel"/>Cancelar</button><button class="bio-nexus-action bio-nexus-action-primary" :disabled="submitDisabled" @click="submit"><BioNexusActionIcon action="save"/>{{saving?'Guardando...':mode==='create'?'Crear':'Guardar'}}</button></template>
  </BioNexusDialog>
  <BioNexusConfirmDialog ref="discardDialog" />
  <ExamDetailDialog ref="detailDialog" />
</template>
<script setup>
import ExamDetailDialog from "@/components/exams/ExamDetailDialog.vue";
import{computed,nextTick,reactive,ref}from'vue';import BioNexusDialog from'@/components/ui/BioNexusDialog.vue';import BioNexusFormField from'@/components/ui/BioNexusFormField.vue';import BioNexusActionIcon from'@/components/ui/BioNexusActionIcon.vue';import BioNexusActionButton from'@/components/ui/BioNexusActionButton.vue';import BioNexusConfirmDialog from'@/components/ui/BioNexusConfirmDialog.vue';import BioNexusFormLayout from'@/components/ui/BioNexusFormLayout.vue';import BioNexusFormErrors from'@/components/ui/BioNexusFormErrors.vue';
const props=defineProps({saving:Boolean,canCreate:Boolean,canUpdate:Boolean,canManageItems:Boolean,exams:{type:Array,default:()=>[]}}),emit=defineEmits(['submit']),dialog=ref(null),discardDialog=ref(null),detailDialog=ref(null),firstInput=ref(null),mode=ref('create'),current=ref(null),search=ref(''),attempted=ref(false),errorMessage=ref(''),original=ref(''),originalItems=ref([]),draft=reactive({description:'',details:'',items:[]});
const values=computed(()=>({description:draft.description.trim(),details:draft.details.trim()})),signature=computed(()=>JSON.stringify({...values.value,items:draft.items.map(item=>[item.examId,item.description])})),changed=computed(()=>signature.value!==original.value),descriptionError=computed(()=>attempted.value&&!values.value.description?'La descripción es obligatoria.':''),submitDisabled=computed(()=>props.saving||(mode.value==='create'?(!props.canCreate||!values.value.description||!draft.items.length):(signature.value===original.value||!props.canUpdate&&!props.canManageItems))),available=computed(()=>{const query=search.value.trim().toLowerCase(),used=new Set(draft.items.map(item=>item.examId));return props.exams.filter(exam=>!exam.annulled&&!used.has(exam.id)&&(!query||`${exam.description} ${exam.abbreviation||''}`.toLowerCase().includes(query)))});
function assign(row){draft.description=row?.description||'';draft.details=row?.details||'';draft.items=(row?.grouphtitems||[]).map(item=>({...item,description:item.description||props.exams.find(exam=>exam.id===item.examId)?.description||`Examen ${item.examId}`,abbreviation:props.exams.find(exam=>exam.id===item.examId)?.abbreviation||''}));originalItems.value=(row?.grouphtitems||[]).map(item=>({...item}))}async function show(){await dialog.value?.open();await nextTick();original.value=signature.value;firstInput.value?.focus()}async function openCreate(){mode.value='create';current.value=null;assign(null);search.value='';attempted.value=false;errorMessage.value='';await show()}async function openEdit(row){mode.value='edit';current.value=row;assign(row);search.value='';attempted.value=false;errorMessage.value='';await show()}function syncDirty(){}function add(exam){draft.items.push({examId:exam.id,description:exam.description,abbreviation:exam.abbreviation});}function remove(index){draft.items.splice(index,1)}function openDetail(exam) { detailDialog.value?.open(exam); }function submit(){attempted.value=true;if(descriptionError.value||!draft.items.length||submitDisabled.value)return;emit('submit',{mode:mode.value,record:current.value,group:values.value,items:draft.items.map(item=>({examId:item.examId,description:item.description})),originalItems:originalItems.value})}async function requestClose(){if(props.saving)return;if(changed.value){const confirmed=await discardDialog.value?.ask({kicker:'Confirmación',title:'Descartar cambios',message:'Hay cambios sin guardar. ¿Deseas salir y descartarlos?',icon:'warning',variant:'danger',confirmIcon:'delete',confirmText:'Sí, salir y descartar cambios',cancelText:'Cancelar'});if(!confirmed)return}dialog.value?.close()}function close(){dialog.value?.close()}function reset(){attempted.value=false}function setError(value){errorMessage.value=String(value||'')}function clearError(){errorMessage.value=''}defineExpose({openCreate,openEdit,close,setError,clearError})
</script>
<style scoped>.worksheet-body{display:grid;gap:10px;font:400 13px var(--bio-nexus-font-family,Inter,Roboto,Arial,sans-serif)}.worksheet-fields,.worksheet-picker{display:grid;grid-template-columns:minmax(340px,.95fr) minmax(460px,1.25fr);gap:12px}.worksheet-fields textarea{min-height:64px}.worksheet-panel{display:grid;grid-template-rows:auto minmax(0,1fr);gap:7px;min-height:0;padding:10px;border:1px solid var(--bio-nexus-color-border);border-radius:var(--bio-nexus-radius-md);background:var(--bio-nexus-color-surface)}.worksheet-panel header{display:flex;justify-content:space-between;align-items:center;min-height:38px}.worksheet-list{display:grid;align-content:start;gap:6px;height:clamp(340px,48vh,500px);overflow-y:auto;padding:2px 5px 8px 1px}.worksheet-row{display:flex;align-items:center;gap:8px;min-height:46px;padding:5px 8px;border:1px solid var(--bio-nexus-color-border);border-radius:var(--bio-nexus-radius-sm);background:var(--bio-nexus-color-surface-soft)}.catalog-mark,.order-number{display:grid;place-items:center;flex:0 0 32px;width:32px;height:32px;border:1px solid var(--bio-nexus-color-border-strong);border-radius:50%;background:var(--bio-nexus-color-surface);color:var(--bio-nexus-color-primary);font-weight:700}.row-copy{display:grid;min-width:0;flex:1}.row-copy strong,.row-copy small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row-copy small{color:var(--bio-nexus-color-text-muted);font-size:11px}.available-actions{display:flex;align-items:center;gap:4px;flex:none}.remove{min-height:32px;padding:0 9px;border:1px solid var(--bio-nexus-color-border);border-radius:var(--bio-nexus-radius-sm);background:var(--bio-nexus-color-surface);font:600 12px var(--bio-nexus-font-family);color:var(--bio-nexus-color-danger);cursor:pointer}.worksheet-empty{padding:18px;text-align:center;color:var(--bio-nexus-color-text-muted)}.worksheet-error{margin:0;color:var(--bio-nexus-color-danger)}.detail-grid{display:grid;gap:10px}.detail-grid article{display:grid;gap:4px;padding:12px;border:1px solid var(--bio-nexus-color-border);border-radius:var(--bio-nexus-radius-md)}.detail-grid span{color:var(--bio-nexus-color-text-muted);font-size:12px;font-weight:700}@media(max-width:900px){.worksheet-fields,.worksheet-picker{grid-template-columns:1fr}.worksheet-list{height:360px}}</style>
<style>dialog.bio-nexus-dialog.worksheet-entry-dialog{width:min(1320px,calc(100vw - 32px))!important;height:min(820px,calc(100dvh - 32px))!important;max-height:calc(100dvh - 32px)!important}.worksheet-entry-shell{height:100%!important}.worksheet-entry-body{min-height:0;overflow:auto;padding:12px 16px!important}</style>
