function id(value) { const parsed = Number(value); return Number.isInteger(parsed) && parsed > 0 ? parsed : 0; }
function text(value) { return typeof value === "string" ? value.trim() : ""; }
function money(value) { const parsed = Number(value); return Number.isFinite(parsed) && parsed >= 0 ? Math.round(parsed * 100) / 100 : 0; }
function flag(value) { return value === true || value === 1 || value === "1"; }
export function normalizeExamGroup(value = {}) { return { id: id(value.id), description: text(value.description), position: Number(value.position) || 0, its_exam: flag(value.its_exam), annulled: flag(value.annulled) }; }
export function normalizeExamGroups(value) { const rows = Array.isArray(value) ? value : Array.isArray(value?.data) ? value.data : []; return rows.map(normalizeExamGroup).filter((row) => row.id > 0).sort((a, b) => a.position - b.position || a.description.localeCompare(b.description)); }
export function normalizeExam(value = {}) { return { id: id(value.id), group_id: id(value.group_id), description: text(value.description), abbreviation: text(value.abbreviation), position: Number(value.position) || 0, special_test: flag(value.special_test), tax_id: Number.isInteger(Number(value.tax_id)) ? Number(value.tax_id) : 0, cost1: money(value.cost1), cost2: money(value.cost2), cost3: money(value.cost3), cost4: money(value.cost4), cost5: money(value.cost5), cost6: money(value.cost6), annulled: flag(value.annulled), work_sheet: typeof value.work_sheet === "string" ? value.work_sheet : null, format: typeof value.format === "string" ? value.format : null, format_vue: value.format_vue ?? null }; }
export function normalizeExams(value) { const rows = Array.isArray(value) ? value : Array.isArray(value?.data) ? value.data : []; return rows.map(normalizeExam).filter((row) => row.id > 0); }
export function normalizeTax(value = {}) { return { id: id(value.id), description: text(value.description), value: money(value.value), hide: flag(value.hide) }; }
export function normalizeTaxes(value) { const rows = Array.isArray(value) ? value : Array.isArray(value?.data) ? value.data : []; return rows.map(normalizeTax).filter((row) => row.id > 0 && !row.hide); }
export function normalizeExamSearchResult(value = {}) { return { id: id(value.id), group_id: id(value.group_id), description: text(value.description), abbreviation: text(value.abbreviation), annulled: flag(value.annulled), group_description: text(value.group_description), group_annulled: flag(value.group_annulled) }; }
export function normalizeExamSearchResults(value) { const rows = Array.isArray(value) ? value : Array.isArray(value?.data) ? value.data : []; return rows.map(normalizeExamSearchResult).filter((row) => row.id > 0 && row.group_id > 0); }
