import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
const read = (file) => fs.readFileSync(path.join(process.cwd(), file), "utf8");
const view = read("src/views/TaxesView.vue");
for (const field of ["only_dollars", "always_subtotal", "hide"]) assert.ok(view.includes(`toggleBoolean(row, "${field}")`));
assert.ok(view.includes('row.only_dollars ? "Desactivar Solo dolares" : "Activar Solo dolares"'));
assert.ok(view.includes('row.always_subtotal ? "Desactivar Fijo en subtotal" : "Activar Fijo en subtotal"'));
assert.ok(view.includes('row.hide ? "Mostrar impuesto" : "Ocultar impuesto"'));
assert.ok(view.includes('exportAlignment: "center"'));
assert.ok(view.includes('exportHeaderAlignment: "center"'));
assert.ok(view.includes('cellStyle: { textAlign: "center" }'));
assert.ok(view.includes("...exportOptions"));
assert.ok(!view.includes("...exportOptions,rn"));
assert.equal((view.match(/const contextItems = computed/g) || []).length, 1);
assert.equal((view.match(/function toggleColumn\(/g) || []).length, 1);
console.log("Tax structural context and export contract approved.");