import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
const read=(file)=>fs.readFileSync(path.join(process.cwd(),file),"utf8");
const view=read("src/views/TaxesView.vue");
for(const permission of ["tax.create","tax.update","tax.delete"]) assert.ok(view.includes(permission));
for(const field of ["only_dollars","always_subtotal","hide"]) assert.ok(view.includes(`toggleColumn("${field}"`));
assert.ok(view.includes("BioNexusContextMenu"));
assert.ok(view.includes('@row-context-menu="openContextMenu"'));
assert.ok(view.includes("contextItems"));
assert.ok(view.includes("onToggle: (row) => toggleBoolean(row, field)"));
assert.ok(view.includes('headerClass: "tax-center-header"'));
assert.ok(view.includes('cellClass: "tax-center-cell"'));
assert.ok(view.includes("async function toggleBoolean"));
console.log("Tax frontend interaction contract approved.");